### ISSUE TITLE
Unify logging throughout sns_ik_lib

### ISSUE THREAD

**Issue by rethink-forrest** [RethinkRobotics-opensource/sns_ik#38]
As of now, some of the logging output is via std::out and some is via ROS logging. Since this will become a stand alone Debian package independent of ROS, I recommend removing ROS logging and using std::out wrapped in a #define, something like SNS_LOG_OUTPUT.

**Comment by MatthewPeterKelly** [comment]
In #47 @IanTheEngineer pointed out that we depend on ROS for communication with the param server. If we need to have ROS as a dependency, then I propose that we switch to ROS logging throughout the package. On the other hand, if we can completely remove ROS as a dependency, then it would make sense to use some other logging utility (either make our own macro or find a lightweight logging library).

**Comment by IanTheEngineer** [comment]
I'm in favor of using ROS logging througout, and replacing it if/when there is a need, rather than preemptively. MoveIt just wrestled with this same issue: https://github.com/ros-planning/moveit/issues/860

**Comment by chris-smith** [comment]
Seems like this has been fixed
