### ISSUE TITLE
remove #define for floating point numerical type

### ISSUE THREAD

**Issue by MatthewPeterKelly** [RethinkRobotics-opensource/sns_ik#65]
**Request:**  remove the pre-processor flag to switch between `float` and `double` in the core math utilities and standardize to using double-precision floating point throughout.
@rethink-forrest @IanTheEngineer -- thoughts?

**Details:**
In `sns_ik_math_utils` we use a pre-processor flag to switch between `float` and `double` for the core math utilities. This is a bad idea for several reasons:
- there is huge loss in accuracy for doing single (vs double) precision arithmetic
- single precision math is not faster than double, and is actually slower on some hardware
- using a preprocessor flag means that people need to recompile the library to use the single-precision version
- when I tried to compile in single precision mode the compiler reported several errors
- the one place where using scalar precision would make sense is on an embedded processor that only had a single-precision floating point unit... but then we would need to replace all doubles with floats, not just some of them.

The simplest solution would be to remove the pre-processor flag and use double precision floating point in the entire library. 
- pro: simplifies the library, both from a documentation and use perspective
- pro: prevents people from naively switching to single precision without checking that it actually speeds up their code
- pro: KDL (which we call for Jacobians) uses double in the background
- con: technically it would break the API because we would remove the "Scalar" type and just use double instead. That being said, we don't currently expect users to be messing around with the internal math utilities. There is one public method in the SNS_IK class that uses the Scalar type, but the intera code base is hard coded to pass in a double (so it would break if we switched the pre-processor flag...).

Another solution would be to implement the entire library as a template library like Eigen.  I do not suggest that we do this.
- pro: robust ability to switch data types
- con: significantly more difficult to implement and debug
- con: significantly more difficult for new users to read and understand source code.

**Comment by IanTheEngineer** [comment]
This breaks the private API, rather than the public., so I don't see an issue with moving forward on your proposed change.

**Comment by MatthewPeterKelly** [comment]
commit c1f5f7bbc9366995923ec8e92af575a931cbaa01
Author: Matthew Kelly <matthew.kelly2@gmail.com>
Date:   Mon May 7 15:33:29 2018 -0400

    Remove preprocessor switch float vs double (#70)
    
    * Remove preprocessor switch float vs double
    
    The key change in this commit is to replace the preprocessor
    flag that switched between using float and double precision.
    
    It does not make any change to the implementation or documentation.
    
    There were several small code clean-ups included as well:
    - use standard Eigen typedefs (rather than custom)
    - remove "using namespace Eigen"
    - fix the scoping on local constants
    - replace #define INF with numeric_limits<>::max()
    
    *Code changes are based on the Google C++ style guide.
